# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7cf36f57e6807c63b2318831a9036365905132be2d0ffc6da1a3796ea5a78cf1a3d08ab55ee6661b04b0eb447ede40a0aef59b8e768752ca936392cde45043c

test:
  secret_key_base: a6f97fd65393ed02a742e6bb0b5e945726ea5b1382b89a522f910389aafe58239d004a94cdd0168cb9ed4bdfd85cc196819fb50436aa6392db866d3df7551edd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
